### ISSUE TITLE
Support a user/team/global configuration

### ISSUE THREAD

**Issue by acaloiaro** [acaloiaro/prwatch-action#25]
As a user --
- I want commenting enabled, but not status transitions 

As a team -- 
- I want to be able to control all settings for every member of the team

As an org --
- I want to control everything for everyone 

Global permissions supercede team-level permissions, and team-level permissions supercede user-level permissions. 

Teams/users refer to Github users and teams.

For team settings -- 
* On boot, pull all members of team so PR authors' membership can be checked against team user lists. 

This should be done through a new configuration YAML file. 

```yaml
settings:
  issue_transitions: 
    enabled: true 
  issue_comments:
    enabled: true
teams:
  - name: team 1
    settings:
      issue_transitions:
        enabled: false 
      issue_comments: 
        enabled: false
users:
  - user: acaloiaro
     settings:
       issue_transitions:
         enabled: false
       issue_comments: 
         enabled: true
```

Team-level permissions are a nice-to-have. Initially build out global and user-level perms.
